services:
  - type: web
    name: gtrsb
    env: python
    rootDir: ver0.2
    buildCommand: cd ver0.2 && pip install -r requirements.txt
    startCommand: cd ver0.2 && gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py 